version: "3.9"
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_PROD_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  backend:
    depends_on:
      - "db"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_PROD_DB_NAME}"

    build:
      context: .
      dockerfile: app/dockerfile
    ports:
      - "80:80"

